# Generated by Django 3.2 on 2020-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestmethod', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsnum', models.IntegerField()),
                ('tsppro', models.CharField(max_length=10)),
                ('tsurl', models.CharField(max_length=100)),
                ('isPass', models.BooleanField()),
            ],
        ),
    ]
