# Generated by Django 3.2 on 2020-09-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMethod',
        ),
        migrations.DeleteModel(
            name='TestPro',
        ),
    ]
