# Generated by Django 3.0.5 on 2020-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tsdemo', '0002_auto_20200927_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsnum', models.IntegerField()),
                ('tsppro', models.CharField(max_length=10)),
                ('tsurl', models.CharField(max_length=100)),
                ('ispass', models.BooleanField(default=True)),
            ],
        ),
    ]
