# Generated by Django 3.0.5 on 2020-10-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0004_auto_20200930_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpro',
            name='brnum',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testpro',
            name='tsdesc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
