# Generated by Django 3.0.5 on 2020-10-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0005_auto_20201001_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpro',
            name='brnum',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
