# Generated by Django 3.0.5 on 2020-10-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0006_auto_20201001_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpro',
            name='brnum',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
