# Generated by Django 3.0.5 on 2020-10-01 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0007_auto_20201001_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpro',
            name='brnum',
            field=models.CharField(max_length=10, null=True, verbose_name='BR号'),
        ),
        migrations.AlterField(
            model_name='testpro',
            name='isPass',
            field=models.BooleanField(default=True, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='testpro',
            name='tsdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='testpro',
            name='tsdesc',
            field=models.CharField(max_length=100, null=True, verbose_name='案例描述'),
        ),
        migrations.AlterField(
            model_name='testpro',
            name='tsnum',
            field=models.IntegerField(verbose_name='案例编号'),
        ),
        migrations.AlterField(
            model_name='testpro',
            name='tsppro',
            field=models.CharField(max_length=10, verbose_name='所属茶农'),
        ),
        migrations.AlterField(
            model_name='testpro',
            name='tsurl',
            field=models.CharField(max_length=100, verbose_name='接口地址'),
        ),
    ]
