# Generated by Django 3.0.5 on 2020-10-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0009_auto_20201001_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpro',
            name='brsprint',
            field=models.CharField(max_length=10, null=True, verbose_name='所属迭代'),
        ),
        migrations.AddField(
            model_name='testpro',
            name='tsrh',
            field=models.CharField(max_length=100, null=True, verbose_name='接口请求头'),
        ),
        migrations.AddField(
            model_name='testpro',
            name='tsrm',
            field=models.CharField(max_length=8, null=True, verbose_name='请求方式'),
        ),
    ]
