# Generated by Django 3.0.5 on 2020-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0010_auto_20201001_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpro',
            name='tsnum',
            field=models.IntegerField(verbose_name='案例步骤'),
        ),
    ]
