# Generated by Django 3.0.5 on 2020-10-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0011_auto_20201001_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpro',
            name='tsexp',
            field=models.CharField(max_length=100, null=True, verbose_name='期待返回值'),
        ),
        migrations.AddField(
            model_name='testpro',
            name='tspara',
            field=models.CharField(max_length=500, null=True, verbose_name='请求参数'),
        ),
        migrations.AddField(
            model_name='testpro',
            name='tsrefurl',
            field=models.CharField(max_length=300, null=True, verbose_name='Refere Link'),
        ),
    ]
