# Generated by Django 3.0.5 on 2020-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0012_auto_20201002_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brnum', models.CharField(max_length=10, null=True, verbose_name='BR号')),
                ('brsprint', models.CharField(max_length=10, null=True, verbose_name='所属迭代')),
                ('tsdesc', models.CharField(max_length=100, null=True, verbose_name='案例描述')),
                ('tsppro', models.CharField(max_length=10, verbose_name='所属产品')),
                ('tsnum', models.IntegerField(verbose_name='案例步骤')),
                ('tsurl', models.CharField(max_length=100, verbose_name='接口地址')),
                ('tsrm', models.CharField(max_length=8, null=True, verbose_name='请求方式')),
                ('tspara', models.CharField(max_length=500, null=True, verbose_name='请求参数')),
                ('tsrh', models.CharField(max_length=100, null=True, verbose_name='接口请求头')),
                ('tsexp', models.CharField(max_length=100, null=True, verbose_name='期待返回值')),
                ('tsdate', models.DateTimeField(auto_now_add=True, verbose_name='录库时间')),
                ('tsrefurl', models.CharField(max_length=300, null=True, verbose_name='Refere Link')),
                ('isPass', models.BooleanField(default=True, verbose_name='是否通过')),
            ],
        ),
        migrations.DeleteModel(
            name='TestPro',
        ),
    ]
