# Generated by Django 3.0.5 on 2020-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0013_auto_20201002_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='tspara',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='请求参数'),
        ),
    ]
