# Generated by Django 3.0.5 on 2020-10-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0014_auto_20201002_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apitest',
            unique_together={('brnum', 'tsnum', 'tsdesc')},
        ),
    ]
