# Generated by Django 3.0.5 on 2020-10-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsdemo', '0015_auto_20201002_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apitest',
            unique_together={('brnum', 'tsurl')},
        ),
    ]
